// Generated by packages/tokens/build.mjs from tokens/*.json. Do not edit by hand.

export const color = {
  dark: {
  "bg": "#07090b",
  "fg": "#f2f5f8",
  "dim": "#c6ced6",
  "mute": "#9aa5b0",
  "faint": "#7c8791",
  "border": "rgba(255, 255, 255, 0.16)",
  "border2": "rgba(255, 255, 255, 0.28)",
  "panel": "rgba(255, 255, 255, 0.02)",
  "panel2": "rgba(255, 255, 255, 0.045)",
  "bracket": "rgba(255, 255, 255, 0.45)",
  "glow": "rgba(150, 165, 175, 0.10)",
  "accent": "#f7bd63",
  "accentSoft": "rgba(247, 189, 99, 0.16)",
  "accentLine": "rgba(247, 189, 99, 0.5)",
  "accent2": "#7fd8ff",
  "accent2Soft": "rgba(127, 216, 255, 0.16)",
  "accent2Line": "rgba(127, 216, 255, 0.5)"
},
  light: {
  "bg": "#f3f4f5",
  "fg": "#0e1216",
  "dim": "#333c45",
  "mute": "#586269",
  "faint": "#767f88",
  "border": "rgba(0, 0, 0, 0.2)",
  "border2": "rgba(0, 0, 0, 0.32)",
  "panel": "rgba(0, 0, 0, 0.02)",
  "panel2": "rgba(0, 0, 0, 0.05)",
  "bracket": "rgba(0, 0, 0, 0.45)",
  "glow": "rgba(120, 135, 145, 0.12)",
  "accent": "#9a6208",
  "accentSoft": "rgba(154, 98, 8, 0.1)",
  "accentLine": "rgba(154, 98, 8, 0.42)",
  "accent2": "#0d6d92",
  "accent2Soft": "rgba(13, 109, 146, 0.1)",
  "accent2Line": "rgba(13, 109, 146, 0.42)"
},
  alarm: {
  "alarm": "#ff8f6b",
  "alarmSoft": "rgba(255, 143, 107, 0.1)",
  "alarmLine": "rgba(255, 143, 107, 0.4)",
  "alarmInk": "#07090b"
},
} as const;

/** Every color token's kebab-case name, exactly as it appears in tokens.css
 * and the Tailwind theme (e.g. "accent-2-line"). The single source other
 * tooling (cn's tailwind-merge config, lint rules) should read from, rather
 * than re-listing token names by hand. */
export const colorTokenNames = ["bg","fg","dim","mute","faint","border","border-2","panel","panel-2","bracket","glow","accent","accent-soft","accent-line","accent-2","accent-2-soft","accent-2-line","alarm","alarm-soft","alarm-line","alarm-ink"] as const;

export const space = {
  "0": "0px",
  "4": "4px",
  "6": "6px",
  "8": "8px",
  "12": "12px",
  "16": "16px",
  "18": "18px",
  "22": "22px",
  "32": "32px",
  "44": "44px"
} as const;

export const radius = "2px" as const;

export const radiusChip = "20px" as const;

export const font = {
  "heading": "'Space Grotesk', sans-serif",
  "body": "'IBM Plex Mono', monospace"
} as const;

export const fontWeight = {
  "regular": 400,
  "semibold": 600
} as const;

export const text = {
  "display": "48px",
  "title": "28px",
  "metric": "28px",
  "small": "13px",
  "label": "12px",
  "calloutTitle": "14.5px",
  "heading": "24px",
  "micro": "11px",
  "body": "14px",
  "section": "17px",
  "docTitle": "34px"
} as const;

export const leading = {
  "display": 1.08,
  "title": 1.15,
  "metric": 1.1,
  "small": 1.5,
  "label": 1.4,
  "calloutTitle": 1.2,
  "heading": 1.15,
  "micro": 1.4,
  "body": 1.6,
  "section": 1.3,
  "docTitle": 1.1
} as const;

export const tracking = {
  "tight6": "0.06em",
  "tight8": "0.08em",
  "tight10": "0.1em",
  "tight12": "0.12em",
  "tight14": "0.14em",
  "tight16": "0.16em",
  "tight20": "0.2em",
  "tightNeg1": "-0.01em",
  "tightNeg2": "-0.02em"
} as const;

export const icon = {
  "callout": "17px",
  "glyphRail": "22px",
  "glyphTile": "34px",
  "inline": "16px",
  "strokeGlyph": 2.2,
  "strokeInline": 2
} as const;

export const easing = {
  "standard": "cubic-bezier(.4, 0, .2, 1)",
  "symmetric": "cubic-bezier(.45, 0, .55, 1)",
  "draw": "cubic-bezier(.35, 0, .2, 1)"
} as const;

export const duration = {
  "instant": "140ms",
  "control": "180ms",
  "panel": "260ms",
  "reveal": "500ms"
} as const;

export const shadow = {
  "bubble": "0 12px 30px rgba(0, 0, 0, 0.5)",
  "menu": "0 22px 60px rgba(0, 0, 0, 0.45)",
  "overlay": "0 30px 90px rgba(0, 0, 0, 0.5)",
  "overlayHorizontal": "-30px 0 90px rgba(0, 0, 0, 0.5)",
  "hoverLift": "0 3px 10px -4px rgba(0, 0, 0, 0.45)",
  "hoverLiftAccent": "0 4px 12px -4px color-mix(in srgb, var(--accent) 45%, transparent)",
  "press": "inset 0 2px 4px rgba(0, 0, 0, 0.35)",
  "pressPrimary": "inset 0 2px 5px rgba(0, 0, 0, 0.6)"
} as const;

export const zIndex = {
  "chrome": 4,
  "railStub": 36,
  "commandBar": 60,
  "overlay": 80,
  "toast": 90
} as const;

export const breakpoint = {
  "tablet": "640px",
  "desktop": "1024px",
  "wide": "1440px"
} as const;

export const shell = {
  "railWidth": "216px",
  "railWidthCollapsed": "56px",
  "subnavWidth": "214px",
  "headerHeight": "52px"
} as const;

export const popover = {
  "panelWidth": "210px"
} as const;

export const modal = {
  "widthSm": "400px",
  "widthMd": "560px",
  "widthLg": "760px"
} as const;
