// Generated by packages/tokens/build.mjs from tokens/*.json. Do not edit by hand.

export const color = {
  dark: {
  "bg": "#07090b",
  "fg": "#f2f5f8",
  "dim": "#c6ced6",
  "border2": "rgba(255, 255, 255, 0.28)",
  "accent": "#f7bd63",
  "accentSoft": "rgba(247, 189, 99, 0.16)",
  "accentLine": "rgba(247, 189, 99, 0.5)",
  "accent2": "#7fd8ff",
  "accent2Line": "rgba(127, 216, 255, 0.5)"
},
  light: {
  "bg": "#f3f4f5",
  "fg": "#0e1216",
  "dim": "#333c45",
  "border2": "rgba(0, 0, 0, 0.32)",
  "accent": "#9a6208",
  "accentSoft": "rgba(154, 98, 8, 0.1)",
  "accentLine": "rgba(154, 98, 8, 0.42)",
  "accent2": "#0d6d92",
  "accent2Line": "rgba(13, 109, 146, 0.42)"
},
  alarm: {
  "alarm": "#ff8f6b",
  "alarmSoft": "rgba(255, 143, 107, 0.1)",
  "alarmLine": "rgba(255, 143, 107, 0.4)",
  "alarmInk": "#07090b"
},
} as const;

/** Every color token's kebab-case name, exactly as it appears in tokens.css
 * and the Tailwind theme (e.g. "accent-2-line"). The single source other
 * tooling (cn's tailwind-merge config, lint rules) should read from, rather
 * than re-listing token names by hand. */
export const colorTokenNames = ["bg","fg","dim","border-2","accent","accent-soft","accent-line","accent-2","accent-2-line","alarm","alarm-soft","alarm-line","alarm-ink"] as const;

export const space = {
  "4": "4px",
  "6": "6px",
  "8": "8px",
  "12": "12px",
  "16": "16px",
  "18": "18px"
} as const;

export const radius = "2px" as const;

export const font = {
  "heading": "'Space Grotesk', sans-serif",
  "body": "'IBM Plex Mono', monospace"
} as const;

export const fontWeight = {
  "regular": 400,
  "semibold": 600
} as const;

export const text = {
  "small": "13px",
  "label": "12px",
  "calloutTitle": "14.5px"
} as const;

export const leading = {
  "small": 1.5,
  "label": 1.4,
  "calloutTitle": 1.2
} as const;

export const tracking = {
  "tight6": "0.06em"
} as const;

export const icon = {
  "callout": "17px"
} as const;
