import { cva, type VariantProps } from "class-variance-authority";
import type { ComponentPropsWithoutRef, ElementType, ReactNode } from "react";
import { cn } from "../cn";

export type TextVariant = "eyebrow" | "heading" | "body" | "caption";

/**
 * Line-height ships paired with each `text-*` size (Tailwind v4's
 * `--text-X--line-height`, generated by packages/tokens/build.mjs), so no
 * separate `leading-*` class is needed here.
 *
 * Eyebrow and Caption render in `--mute`, not the `--faint` their own prose
 * names: `--faint` only clears "AA large" (3.69:1 in the light theme,
 * measured via axe), short of the 4.5:1 floor normal-size text needs — the
 * same gap apps/docs/components/docs-page/page-header.tsx and section.tsx
 * already route around for the docs chrome itself (LDS-014). `--mute`
 * clears 4.5:1 in both themes. Flagged in text.ts's extractionNotes.
 */
const textVariants = cva("font-body", {
  variants: {
    variant: {
      eyebrow: "text-micro uppercase tracking-tight-20 text-mute",
      heading: "font-heading font-semibold text-heading tracking-tight-neg-2 text-fg",
      body: "text-body text-dim",
      caption: "text-micro uppercase tracking-tight-20 text-mute",
    },
    emphasis: {
      true: "text-fg",
    },
    numeric: {
      true: "font-heading font-semibold tabular-nums",
    },
  },
  defaultVariants: { emphasis: false, numeric: false },
});

export interface TextProps
  extends Omit<ComponentPropsWithoutRef<"span">, "color">,
    VariantProps<typeof textVariants> {
  /** Which role this text plays in the block (Text Variants). */
  variant: TextVariant;
  /** The element this renders as — a heading is an h2 or h3 because of
   * where it sits in the document, not because of its size (Text
   * Accessibility "Structure, not styling"). Defaults to a plain `span`. */
  as?: ElementType;
  /** One step up the ramp to --fg for the clause that matters (Text
   * anatomy #4, "Emphasis"). The system's entire emphasis vocabulary — no
   * bold, no italic, no colour. */
  emphasis?: boolean;
  /** Grotesk with tabular figures, for a number read as a value rather
   * than as prose (Text Content rule 4). */
  numeric?: boolean;
  children: ReactNode;
}

/**
 * Two typefaces and four weights of grey — every other typographic
 * decision is already made (CONTEXT.md, Text). What a block of copy is
 * made of: eyebrow, heading, body, caption.
 */
export function Text({
  variant,
  as: Component = "span",
  emphasis,
  numeric,
  className,
  children,
  ...props
}: TextProps) {
  return (
    <Component
      data-slot="text"
      className={cn(textVariants({ variant, emphasis, numeric }), className)}
      {...props}
    >
      {children}
    </Component>
  );
}
