// Builds CSS custom properties, the Tailwind theme and typed TS exports from
// the DTCG token source in tokens/. Run with `pnpm --filter @lairy/tokens run generate`.
import { mkdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import StyleDictionary from "style-dictionary";
import { formats, transformGroups } from "style-dictionary/enums";

const dir = path.dirname(fileURLToPath(import.meta.url));
const cssDir = path.join(dir, "src/css");
mkdirSync(cssDir, { recursive: true });

const readTokens = (file) => JSON.parse(readFileSync(path.join(dir, file), "utf8"));

const dark = readTokens("tokens/color.dark.json");
const light = readTokens("tokens/color.light.json");
const alarm = readTokens("tokens/color.alarm.json");
const spacing = readTokens("tokens/spacing.json");
const radiusTokens = readTokens("tokens/radius.json");
const typography = readTokens("tokens/typography.json");
const iconTokens = readTokens("tokens/icon.json");

const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const val = (t) => t.$value;

// ---------------------------------------------------------------------------
// 1. CSS custom properties: dark on :root, light on [data-theme="light"].
// ---------------------------------------------------------------------------

function buildCssTheme({ name, source, selector }) {
  return new StyleDictionary({
    source,
    platforms: {
      css: {
        transformGroup: transformGroups.css,
        buildPath: cssDir + "/",
        files: [
          {
            destination: `_${name}.css`,
            format: formats.cssVariables,
            options: { selector, outputReferences: false },
          },
        ],
      },
    },
  });
}

const SHARED = [
  "tokens/spacing.json",
  "tokens/radius.json",
  "tokens/typography.json",
  "tokens/icon.json",
];

const darkSd = buildCssTheme({
  name: "dark",
  source: ["tokens/color.dark.json", "tokens/color.alarm.json", ...SHARED],
  selector: ":root",
});
const lightSd = buildCssTheme({
  name: "light",
  source: ["tokens/color.light.json"],
  selector: '[data-theme="light"]',
});

await darkSd.buildPlatform("css");
await lightSd.buildPlatform("css");

const darkCss = readFileSync(path.join(cssDir, "_dark.css"), "utf8");
const lightCss = readFileSync(path.join(cssDir, "_light.css"), "utf8");
const cssBanner =
  "/* Generated by packages/tokens/build.mjs from tokens/*.json. Do not edit by hand. */\n";
writeFileSync(path.join(cssDir, "tokens.css"), cssBanner + darkCss + "\n" + lightCss);
rmSync(path.join(cssDir, "_dark.css"));
rmSync(path.join(cssDir, "_light.css"));

// ---------------------------------------------------------------------------
// 2. Tailwind v4 theme: resets every default scale, then maps Lairy tokens
//    onto Tailwind's namespaces (ADR-0003).
// ---------------------------------------------------------------------------

const colorNames = [...Object.keys(dark), ...Object.keys(alarm)];

const themeLines = [];
themeLines.push(cssBanner.trim());
themeLines.push("@theme {");
themeLines.push("  /* Remove Tailwind's default theme (ADR-0003): only Lairy tokens exist. */");
for (const ns of [
  "color",
  "spacing",
  "text",
  "font",
  "radius",
  "shadow",
  "tracking",
  "leading",
  "font-weight",
]) {
  themeLines.push(`  --${ns}-*: initial;`);
}
themeLines.push("");
themeLines.push("  /* Color — aliases the themed custom properties in tokens.css. */");
for (const name of colorNames) {
  themeLines.push(`  --color-${name}: var(--${name});`);
}
themeLines.push("");
themeLines.push("  /* Below: direct values, not var() aliases like color above. Radius,");
themeLines.push("     spacing and typography are non-themeable constants with no ADR-0008");
themeLines.push("     name to preserve, so there's nothing for an alias to buy here — only");
themeLines.push("     color needs the indirection, to switch at runtime by theme. */");
themeLines.push("  /* Spacing ramp (docs/prd.md §8.3). */");
for (const [step, t] of Object.entries(spacing.space)) {
  themeLines.push(`  --spacing-${step}: ${val(t)};`);
}
themeLines.push("");
themeLines.push("  /* Radius (locked, docs/prd.md §8.4). */");
themeLines.push(`  --radius-ds: ${val(radiusTokens.radius)};`);
themeLines.push("");
themeLines.push("  /* Font families. next/font/google supplies --ff-<name> at runtime; the");
themeLines.push("     token value is the fallback stack for non-Next consumers. */");
for (const [name, t] of Object.entries(typography.font)) {
  themeLines.push(`  --font-${name}: var(--ff-${name}, ${val(t)});`);
}
themeLines.push("");
themeLines.push("  /* Font weights. */");
for (const [name, t] of Object.entries(typography.weight)) {
  themeLines.push(`  --font-weight-${name}: ${val(t)};`);
}
themeLines.push("");
themeLines.push("  /* Type styles: paired font-size + line-height (docs/prd.md §8.2). */");
for (const [step, t] of Object.entries(typography.text)) {
  themeLines.push(`  --text-${step}: ${val(t)};`);
  const leading = typography.leading[step];
  if (leading) themeLines.push(`  --text-${step}--line-height: ${val(leading)};`);
}
themeLines.push("");
themeLines.push("  /* Tracking steps. */");
for (const [name, t] of Object.entries(typography.tracking)) {
  themeLines.push(`  --tracking-${name}: ${val(t)};`);
}
themeLines.push("}");
writeFileSync(path.join(cssDir, "tailwind-theme.css"), themeLines.join("\n") + "\n");

// ---------------------------------------------------------------------------
// 3. Typed TS exports, for consumers that need raw values (tests, non-Tailwind
//    contexts). Colors are keyed by theme; everything else is theme-independent.
// ---------------------------------------------------------------------------

const colorObject = (tokens) => {
  const out = {};
  for (const [name, t] of Object.entries(tokens)) out[camel(name)] = val(t);
  return out;
};
const flatObject = (tokens) => {
  const out = {};
  for (const [name, t] of Object.entries(tokens)) out[camel(name)] = val(t);
  return out;
};

const tsBanner =
  "// Generated by packages/tokens/build.mjs from tokens/*.json. Do not edit by hand.\n";
const ts = `${tsBanner}
export const color = {
  dark: ${JSON.stringify(colorObject(dark), null, 2)},
  light: ${JSON.stringify(colorObject(light), null, 2)},
  alarm: ${JSON.stringify(colorObject(alarm), null, 2)},
} as const;

/** Every color token's kebab-case name, exactly as it appears in tokens.css
 * and the Tailwind theme (e.g. "accent-2-line"). The single source other
 * tooling (cn's tailwind-merge config, lint rules) should read from, rather
 * than re-listing token names by hand. */
export const colorTokenNames = ${JSON.stringify([...Object.keys(dark), ...Object.keys(alarm)])} as const;

export const space = ${JSON.stringify(flatObject(spacing.space), null, 2)} as const;

export const radius = ${JSON.stringify(val(radiusTokens.radius))} as const;

export const font = ${JSON.stringify(flatObject(typography.font), null, 2)} as const;

export const fontWeight = ${JSON.stringify(flatObject(typography.weight), null, 2)} as const;

export const text = ${JSON.stringify(flatObject(typography.text), null, 2)} as const;

export const leading = ${JSON.stringify(flatObject(typography.leading), null, 2)} as const;

export const tracking = ${JSON.stringify(flatObject(typography.tracking), null, 2)} as const;

export const icon = ${JSON.stringify(flatObject(iconTokens.icon), null, 2)} as const;
`;
writeFileSync(path.join(dir, "src/tokens.generated.ts"), ts);

console.log(
  "Tokens built: src/css/tokens.css, src/css/tailwind-theme.css, src/tokens.generated.ts",
);
